### ISSUE TITLE
Motion Senor Setting recommendation

### ISSUE THREAD

**Issue by seaverd** [marc-gist/node-red-contrib-xiaomi-sensors#1]
Thanks for this palate!

Looking for recommendation on motion sensor settings.  Do you have a recommendation for the zigbee2mqtt settings?   Your instructions for the motion node say  send occupancy=false.   Is this a zigbee2mqtt setting?   If so is it this:  occupancy_timeout: 0

Your instructions then say you can extend it by configuring the node for X seconds more.   Do you have any recommendation for how many seconds?

Thanks,
Dan

**Comment by marc-gist** [comment]
you can set timeouts in zigbee2mqtt for motion sensors.
I typically then use the occupancy_timeout... so for something that i want lights to stay on while there might be little motion (say sitting in an office chair), i set the timeout parameter to like 10-15 minutes.
